// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/menu/menu.proto

package menu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Available     bool                   `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_api_menu_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_api_menu_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_api_menu_menu_proto_rawDescGZIP(), []int{0}
}

func (x *Menu) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Menu) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Menu) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Menu) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Menu) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type GetMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuId        string                 `protobuf:"bytes,1,opt,name=menu_id,json=menuId,proto3" json:"menu_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuRequest) Reset() {
	*x = GetMenuRequest{}
	mi := &file_api_menu_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuRequest) ProtoMessage() {}

func (x *GetMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_menu_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuRequest.ProtoReflect.Descriptor instead.
func (*GetMenuRequest) Descriptor() ([]byte, []int) {
	return file_api_menu_menu_proto_rawDescGZIP(), []int{1}
}

func (x *GetMenuRequest) GetMenuId() string {
	if x != nil {
		return x.MenuId
	}
	return ""
}

type GetMenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menu          *Menu                  `protobuf:"bytes,1,opt,name=menu,proto3" json:"menu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuResponse) Reset() {
	*x = GetMenuResponse{}
	mi := &file_api_menu_menu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuResponse) ProtoMessage() {}

func (x *GetMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_menu_menu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuResponse.ProtoReflect.Descriptor instead.
func (*GetMenuResponse) Descriptor() ([]byte, []int) {
	return file_api_menu_menu_proto_rawDescGZIP(), []int{2}
}

func (x *GetMenuResponse) GetMenu() *Menu {
	if x != nil {
		return x.Menu
	}
	return nil
}

type CreateMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Available     bool                   `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuRequest) Reset() {
	*x = CreateMenuRequest{}
	mi := &file_api_menu_menu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuRequest) ProtoMessage() {}

func (x *CreateMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_menu_menu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuRequest.ProtoReflect.Descriptor instead.
func (*CreateMenuRequest) Descriptor() ([]byte, []int) {
	return file_api_menu_menu_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMenuRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMenuRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMenuRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateMenuRequest) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type CreateMenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menu          *Menu                  `protobuf:"bytes,1,opt,name=menu,proto3" json:"menu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuResponse) Reset() {
	*x = CreateMenuResponse{}
	mi := &file_api_menu_menu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuResponse) ProtoMessage() {}

func (x *CreateMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_menu_menu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuResponse.ProtoReflect.Descriptor instead.
func (*CreateMenuResponse) Descriptor() ([]byte, []int) {
	return file_api_menu_menu_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMenuResponse) GetMenu() *Menu {
	if x != nil {
		return x.Menu
	}
	return nil
}

var File_api_menu_menu_proto protoreflect.FileDescriptor

const file_api_menu_menu_proto_rawDesc = "" +
	"\n" +
	"\x13api/menu/menu.proto\x12\x04menu\"\x80\x01\n" +
	"\x04Menu\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\bR\tavailable\")\n" +
	"\x0eGetMenuRequest\x12\x17\n" +
	"\amenu_id\x18\x01 \x01(\tR\x06menuId\"1\n" +
	"\x0fGetMenuResponse\x12\x1e\n" +
	"\x04menu\x18\x01 \x01(\v2\n" +
	".menu.MenuR\x04menu\"}\n" +
	"\x11CreateMenuRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1c\n" +
	"\tavailable\x18\x04 \x01(\bR\tavailable\"4\n" +
	"\x12CreateMenuResponse\x12\x1e\n" +
	"\x04menu\x18\x01 \x01(\v2\n" +
	".menu.MenuR\x04menu2\x86\x01\n" +
	"\vMenuService\x12?\n" +
	"\n" +
	"CreateMenu\x12\x17.menu.CreateMenuRequest\x1a\x18.menu.CreateMenuResponse\x126\n" +
	"\aGetMenu\x12\x14.menu.GetMenuRequest\x1a\x15.menu.GetMenuResponseB-Z+github.com/fahemhakikikhaya/common/api/menub\x06proto3"

var (
	file_api_menu_menu_proto_rawDescOnce sync.Once
	file_api_menu_menu_proto_rawDescData []byte
)

func file_api_menu_menu_proto_rawDescGZIP() []byte {
	file_api_menu_menu_proto_rawDescOnce.Do(func() {
		file_api_menu_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_menu_menu_proto_rawDesc), len(file_api_menu_menu_proto_rawDesc)))
	})
	return file_api_menu_menu_proto_rawDescData
}

var file_api_menu_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_menu_menu_proto_goTypes = []any{
	(*Menu)(nil),               // 0: menu.Menu
	(*GetMenuRequest)(nil),     // 1: menu.GetMenuRequest
	(*GetMenuResponse)(nil),    // 2: menu.GetMenuResponse
	(*CreateMenuRequest)(nil),  // 3: menu.CreateMenuRequest
	(*CreateMenuResponse)(nil), // 4: menu.CreateMenuResponse
}
var file_api_menu_menu_proto_depIdxs = []int32{
	0, // 0: menu.GetMenuResponse.menu:type_name -> menu.Menu
	0, // 1: menu.CreateMenuResponse.menu:type_name -> menu.Menu
	3, // 2: menu.MenuService.CreateMenu:input_type -> menu.CreateMenuRequest
	1, // 3: menu.MenuService.GetMenu:input_type -> menu.GetMenuRequest
	4, // 4: menu.MenuService.CreateMenu:output_type -> menu.CreateMenuResponse
	2, // 5: menu.MenuService.GetMenu:output_type -> menu.GetMenuResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_menu_menu_proto_init() }
func file_api_menu_menu_proto_init() {
	if File_api_menu_menu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_menu_menu_proto_rawDesc), len(file_api_menu_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_menu_menu_proto_goTypes,
		DependencyIndexes: file_api_menu_menu_proto_depIdxs,
		MessageInfos:      file_api_menu_menu_proto_msgTypes,
	}.Build()
	File_api_menu_menu_proto = out.File
	file_api_menu_menu_proto_goTypes = nil
	file_api_menu_menu_proto_depIdxs = nil
}
